[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
dotenvy = "0.15"
serde = "1"
tokio = { version = "1", features = ["full"]}
warp = "0.3"

prisma = { path = "../crates/prisma" }